//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignDB_UI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings_DESKTOP_N41Q35G : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings_DESKTOP_N41Q35G defaultInstance = ((Settings_DESKTOP_N41Q35G)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings_DESKTOP_N41Q35G())));
        
        public static Settings_DESKTOP_N41Q35G Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=S011DDB0003;Initial Catalog=CommonBE;Persist Security Info=True;User " +
            "ID=support_eng;Password=AccessB#")]
        public string CommonBEConnectionString {
            get {
                return ((string)(this["CommonBEConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int UserIndex {
            get {
                return ((int)(this["UserIndex"]));
            }
            set {
                this["UserIndex"] = value;
            }
        }
    }
}
